[package]
name = "clr_rust"
version = "0.1.0"
authors = ["tyler.laing"]

[dependencies]
libc = "*"
winapi = { version = "0.3.5", features = ["guiddef", "winerror"]}

[build-dependencies]
serde_json = "1.0"
